# fly.toml app configuration file generated for plain-nextjs-app on 2025-06-07T15:36:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plain-nextjs-app'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
